version: '3.9'

services:
  web:
    image: dunglas/frankenphp:1-php8.3
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD:/app

networks:
  internal:
